#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2017

services:
  - mssql2017
  - mysql

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: del -Recurse -Force .nuget
  - ps: dotnet test --test-adapter-path:. --logger:Appveyor .\Dapper.Extensions.Linq.sln /restore
  - ps: dotnet pack .\Dapper.Extensions.Linq.sln /p:Configuration=Release /restore

#---------------------------------#
# Tests
#---------------------------------#
test: off

#---------------------------------#
#  Pull Requests                  #
#---------------------------------#
pull_requests:
  do_not_increment_build_number: true

#---------------------------------#
#  General                        #
#---------------------------------#
skip_branch_with_pr: true

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

artifacts:
  - path: '**\*.nupkg'