#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2019

services:
  - mssql2017
  - mysql

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Target AppVeyor

#---------------------------------#
# Tests
#---------------------------------#
test: off

#---------------------------------#
#  Pull Requests                  #
#---------------------------------#
pull_requests:
  do_not_increment_build_number: true

#---------------------------------#
#  General                        #
#---------------------------------#
skip_branch_with_pr: true

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/
